-- Optimus Sun v3 - schema 0001
-- Target: MySQL 8.0.46, InnoDB, utf8mb4_0900_ai_ci
-- Applied only by migration_v3 to an explicitly configured test schema.

CREATE TABLE schema_version (
    VERSION VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL PRIMARY KEY,
    DDL_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STRUCTURE_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    APPLIED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    DESCRIPTION VARCHAR(255) NOT NULL
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE manufacturer (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(150) NOT NULL,
    NAME_NORMALIZED VARCHAR(150)
        GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(NAME, '[[:space:]]+', ' '))) STORED,
    CATEGORY TINYINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_manufacturer_name_normalized (NAME_NORMALIZED),
    CONSTRAINT chk_manufacturer_category CHECK (CATEGORY IN (0, 1, 2))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODEL VARCHAR(255) NOT NULL,
    MODEL_NORMALIZED VARCHAR(255)
        GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(MODEL, '[[:space:]]+', ' '))) STORED,
    MANUFACTURER_ID INT UNSIGNED NOT NULL,
    DIM_WIDTH DECIMAL(10,2) NULL,
    DIM_HEIGHT DECIMAL(10,2) NULL,
    DIM_DEPTH DECIMAL(10,2) NULL,
    DIM_WEIGHT DECIMAL(10,2) NULL,
    MAX_OPERATING_TEMPERATURE DECIMAL(6,2) NULL,
    MIN_OPERATING_TEMPERATURE DECIMAL(6,2) NULL,
    COOLING_MODE VARCHAR(150) NULL,
    PROTECTION_DEGREE VARCHAR(100) NULL,
    TOPOLOGY VARCHAR(150) NULL,
    OVERLOAD DECIMAL(7,2) NULL,
    NUMBER_OF_TRACKERS SMALLINT UNSIGNED NULL,
    NUMBER_OF_INPUTS SMALLINT UNSIGNED NULL,
    NUMBER_OF_BATTERY_INPUTS SMALLINT UNSIGNED NULL,
    MAX_EFFICIENCY DECIMAL(6,2) NULL,
    EURO_EFFICIENCY DECIMAL(6,2) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    ROW_VERSION INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_inverter_manufacturer_model (MANUFACTURER_ID, MODEL_NORMALIZED),
    KEY idx_inverter_model (MODEL),
    KEY idx_inverter_active (ACTIVE),
    CONSTRAINT fk_inverter_manufacturer FOREIGN KEY (MANUFACTURER_ID)
        REFERENCES manufacturer (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_inverter_dimensions CHECK (
        (DIM_WIDTH IS NULL OR DIM_WIDTH >= 0) AND
        (DIM_HEIGHT IS NULL OR DIM_HEIGHT >= 0) AND
        (DIM_DEPTH IS NULL OR DIM_DEPTH >= 0) AND
        (DIM_WEIGHT IS NULL OR DIM_WEIGHT >= 0)
    ),
    CONSTRAINT chk_inverter_temperature CHECK (
        MIN_OPERATING_TEMPERATURE IS NULL OR MAX_OPERATING_TEMPERATURE IS NULL OR
        MIN_OPERATING_TEMPERATURE <= MAX_OPERATING_TEMPERATURE
    ),
    CONSTRAINT chk_inverter_percentages CHECK (
        (OVERLOAD IS NULL OR OVERLOAD >= 0) AND
        (MAX_EFFICIENCY IS NULL OR MAX_EFFICIENCY BETWEEN 0 AND 100) AND
        (EURO_EFFICIENCY IS NULL OR EURO_EFFICIENCY BETWEEN 0 AND 100)
    ),
    CONSTRAINT chk_inverter_active CHECK (ACTIVE IN (FALSE, TRUE))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE module (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    MODEL VARCHAR(255) NOT NULL,
    MODEL_NORMALIZED VARCHAR(255)
        GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(MODEL, '[[:space:]]+', ' '))) STORED,
    MANUFACTURER_ID INT UNSIGNED NOT NULL,
    DIM_WIDTH DECIMAL(10,2) NULL,
    DIM_HEIGHT DECIMAL(10,2) NULL,
    DIM_DEPTH DECIMAL(10,2) NULL,
    DIM_WEIGHT DECIMAL(10,2) NULL,
    WP DECIMAL(12,2) NULL,
    VMPP DECIMAL(10,2) NULL,
    IMPP DECIMAL(10,2) NULL,
    VOC DECIMAL(10,2) NULL,
    ISC DECIMAL(10,2) NULL,
    SOLAR_CELLS VARCHAR(100) NULL,
    CELL_TYPE VARCHAR(100) NULL,
    SURFACE_TYPE VARCHAR(100) NULL,
    COEF_PMAX DECIMAL(8,5) NULL,
    COEF_VOC DECIMAL(8,5) NULL,
    COEF_ISC DECIMAL(8,5) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    ROW_VERSION INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_module_manufacturer_model (MANUFACTURER_ID, MODEL_NORMALIZED),
    KEY idx_module_model (MODEL),
    KEY idx_module_active (ACTIVE),
    CONSTRAINT fk_module_manufacturer FOREIGN KEY (MANUFACTURER_ID)
        REFERENCES manufacturer (ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_module_nonnegative CHECK (
        (DIM_WIDTH IS NULL OR DIM_WIDTH >= 0) AND
        (DIM_HEIGHT IS NULL OR DIM_HEIGHT >= 0) AND
        (DIM_DEPTH IS NULL OR DIM_DEPTH >= 0) AND
        (DIM_WEIGHT IS NULL OR DIM_WEIGHT >= 0) AND
        (WP IS NULL OR WP >= 0) AND (VMPP IS NULL OR VMPP >= 0) AND
        (IMPP IS NULL OR IMPP >= 0) AND (VOC IS NULL OR VOC >= 0) AND
        (ISC IS NULL OR ISC >= 0)
    ),
    CONSTRAINT chk_module_active CHECK (ACTIVE IN (FALSE, TRUE))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mppt (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    INVERTER_ID INT UNSIGNED NOT NULL,
    MPPT_INDEX BIGINT UNSIGNED NOT NULL DEFAULT 0,
    NUMBER_OF_INPUTS SMALLINT UNSIGNED NULL,
    MAX_INPUT_VOLTAGE DECIMAL(10,2) NULL,
    MIN_STARTUP_VOLTAGE DECIMAL(10,2) NULL,
    MAX_OPERATING_VOLTAGE DECIMAL(10,2) NULL,
    MIN_OPERATING_VOLTAGE DECIMAL(10,2) NULL,
    MAX_FULL_LOAD_VOLTAGE DECIMAL(10,2) NULL,
    MIN_FULL_LOAD_VOLTAGE DECIMAL(10,2) NULL,
    RATED_INPUT_VOLTAGE DECIMAL(10,2) NULL,
    MAX_SHORT_CIRCUIT_CURRENT_PER_MPPT DECIMAL(10,2) NULL,
    MAX_SHORT_CIRCUIT_CURRENT_PER_STRING DECIMAL(10,2) NULL,
    MAX_OPERATING_CURRENT_PER_MPPT DECIMAL(10,2) NULL,
    MAX_OPERATING_CURRENT_PER_STRING DECIMAL(10,2) NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_mppt_inverter_index (INVERTER_ID, MPPT_INDEX),
    CONSTRAINT fk_mppt_inverter FOREIGN KEY (INVERTER_ID)
        REFERENCES inverter (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT chk_mppt_index CHECK (MPPT_INDEX <> 1),
    CONSTRAINT chk_mppt_nonnegative CHECK (
        (MAX_INPUT_VOLTAGE IS NULL OR MAX_INPUT_VOLTAGE >= 0) AND
        (MIN_STARTUP_VOLTAGE IS NULL OR MIN_STARTUP_VOLTAGE >= 0) AND
        (MAX_OPERATING_VOLTAGE IS NULL OR MAX_OPERATING_VOLTAGE >= 0) AND
        (MIN_OPERATING_VOLTAGE IS NULL OR MIN_OPERATING_VOLTAGE >= 0) AND
        (MAX_FULL_LOAD_VOLTAGE IS NULL OR MAX_FULL_LOAD_VOLTAGE >= 0) AND
        (MIN_FULL_LOAD_VOLTAGE IS NULL OR MIN_FULL_LOAD_VOLTAGE >= 0) AND
        (RATED_INPUT_VOLTAGE IS NULL OR RATED_INPUT_VOLTAGE >= 0) AND
        (MAX_SHORT_CIRCUIT_CURRENT_PER_MPPT IS NULL OR MAX_SHORT_CIRCUIT_CURRENT_PER_MPPT >= 0) AND
        (MAX_SHORT_CIRCUIT_CURRENT_PER_STRING IS NULL OR MAX_SHORT_CIRCUIT_CURRENT_PER_STRING >= 0) AND
        (MAX_OPERATING_CURRENT_PER_MPPT IS NULL OR MAX_OPERATING_CURRENT_PER_MPPT >= 0) AND
        (MAX_OPERATING_CURRENT_PER_STRING IS NULL OR MAX_OPERATING_CURRENT_PER_STRING >= 0)
    ),
    CONSTRAINT chk_mppt_ranges CHECK (
        (MIN_OPERATING_VOLTAGE IS NULL OR MAX_OPERATING_VOLTAGE IS NULL OR MIN_OPERATING_VOLTAGE <= MAX_OPERATING_VOLTAGE) AND
        (MIN_FULL_LOAD_VOLTAGE IS NULL OR MAX_FULL_LOAD_VOLTAGE IS NULL OR MIN_FULL_LOAD_VOLTAGE <= MAX_FULL_LOAD_VOLTAGE)
    )
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter_output_mode (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    OUTPUT_MODE VARCHAR(100) NOT NULL,
    OUTPUT_MODE_NORMALIZED VARCHAR(100)
        GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(OUTPUT_MODE, '[[:space:]]+', ' '))) STORED,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_output_mode_normalized (OUTPUT_MODE_NORMALIZED),
    CONSTRAINT chk_output_mode_active CHECK (ACTIVE IN (FALSE, TRUE))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter_ac_profile (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    INVERTER_ID INT UNSIGNED NOT NULL,
    PROFILE_TYPE VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    OUTPUT_MODE_ID INT UNSIGNED NULL,
    RATED_ACTIVE_POWER DECIMAL(12,2) NULL,
    MAX_ACTIVE_POWER DECIMAL(12,2) NULL,
    MAX_PEAK_ACTIVE_POWER DECIMAL(12,2) NULL,
    RATED_LINE_TO_LINE_VOLTAGE DECIMAL(10,2) NULL,
    RATED_LINE_TO_NEUTRAL_VOLTAGE DECIMAL(10,2) NULL,
    RATED_CURRENT DECIMAL(10,2) NULL,
    MAX_CURRENT DECIMAL(10,2) NULL,
    SWITCHING_TIME DECIMAL(10,2) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DEFAULT BOOLEAN NOT NULL DEFAULT FALSE,
    DEFAULT_SLOT TINYINT
        GENERATED ALWAYS AS (CASE WHEN IS_DEFAULT = TRUE THEN 1 ELSE NULL END) STORED,
    ROW_VERSION INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_ac_profile_one_default (INVERTER_ID, DEFAULT_SLOT),
    KEY idx_ac_profile_inverter_type (INVERTER_ID, PROFILE_TYPE),
    KEY idx_ac_profile_output_mode (OUTPUT_MODE_ID),
    KEY idx_ac_profile_active (INVERTER_ID, ACTIVE),
    CONSTRAINT fk_ac_profile_inverter FOREIGN KEY (INVERTER_ID)
        REFERENCES inverter (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT fk_ac_profile_output_mode FOREIGN KEY (OUTPUT_MODE_ID)
        REFERENCES inverter_output_mode (ID),
    CONSTRAINT chk_ac_profile_type CHECK (PROFILE_TYPE IN ('AC_OUTPUT', 'AC_INPUT', 'EPS_OUTPUT')),
    CONSTRAINT chk_ac_profile_default CHECK (
        IS_DEFAULT = FALSE OR (ACTIVE = TRUE AND PROFILE_TYPE IN ('AC_OUTPUT', 'EPS_OUTPUT'))
    ),
    CONSTRAINT chk_ac_profile_mode CHECK (
        (PROFILE_TYPE = 'AC_INPUT' AND OUTPUT_MODE_ID IS NULL AND IS_DEFAULT = FALSE) OR
        (PROFILE_TYPE IN ('AC_OUTPUT', 'EPS_OUTPUT') AND (ACTIVE = FALSE OR OUTPUT_MODE_ID IS NOT NULL))
    ),
    CONSTRAINT chk_ac_input_minimum CHECK (
        PROFILE_TYPE <> 'AC_INPUT' OR ACTIVE = FALSE OR (
            IS_DEFAULT = FALSE AND OUTPUT_MODE_ID IS NULL AND (
                (RATED_ACTIVE_POWER IS NOT NULL AND RATED_ACTIVE_POWER > 0) OR
                (RATED_CURRENT IS NOT NULL AND RATED_CURRENT > 0) OR
                (RATED_LINE_TO_LINE_VOLTAGE IS NOT NULL AND RATED_LINE_TO_LINE_VOLTAGE > 0) OR
                (RATED_LINE_TO_NEUTRAL_VOLTAGE IS NOT NULL AND RATED_LINE_TO_NEUTRAL_VOLTAGE > 0)
            )
        )
    ),
    CONSTRAINT chk_ac_output_minimum CHECK (
        PROFILE_TYPE = 'AC_INPUT' OR ACTIVE = FALSE OR
        (RATED_ACTIVE_POWER IS NOT NULL AND RATED_ACTIVE_POWER > 0)
    ),
    CONSTRAINT chk_ac_profile_nonnegative CHECK (
        (RATED_ACTIVE_POWER IS NULL OR RATED_ACTIVE_POWER >= 0) AND
        (MAX_ACTIVE_POWER IS NULL OR MAX_ACTIVE_POWER >= 0) AND
        (MAX_PEAK_ACTIVE_POWER IS NULL OR MAX_PEAK_ACTIVE_POWER >= 0) AND
        (RATED_LINE_TO_LINE_VOLTAGE IS NULL OR RATED_LINE_TO_LINE_VOLTAGE >= 0) AND
        (RATED_LINE_TO_NEUTRAL_VOLTAGE IS NULL OR RATED_LINE_TO_NEUTRAL_VOLTAGE >= 0) AND
        (RATED_CURRENT IS NULL OR RATED_CURRENT >= 0) AND
        (MAX_CURRENT IS NULL OR MAX_CURRENT >= 0) AND
        (SWITCHING_TIME IS NULL OR SWITCHING_TIME >= 0)
    ),
    CONSTRAINT chk_ac_profile_booleans CHECK (
        ACTIVE IN (FALSE, TRUE) AND IS_DEFAULT IN (FALSE, TRUE)
    )
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter_battery (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    INVERTER_ID INT UNSIGNED NOT NULL,
    BATTERY_INDEX BIGINT UNSIGNED NOT NULL DEFAULT 0,
    BATTERY_TYPE VARCHAR(150) NULL,
    BATTERY_VOLTAGE_MIN DECIMAL(10,2) NULL,
    BATTERY_VOLTAGE_MAX DECIMAL(10,2) NULL,
    MAX_CHARGE_CURRENT DECIMAL(10,2) NULL,
    MAX_DISCHARGE_CURRENT DECIMAL(10,2) NULL,
    BATTERY_COM VARCHAR(150) NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    ROW_VERSION INT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (ID),
    KEY idx_battery_inverter_index (INVERTER_ID, BATTERY_INDEX),
    KEY idx_battery_active (INVERTER_ID, ACTIVE),
    CONSTRAINT fk_battery_inverter FOREIGN KEY (INVERTER_ID)
        REFERENCES inverter (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT chk_battery_index CHECK (BATTERY_INDEX <> 1),
    CONSTRAINT chk_battery_values CHECK (
        (BATTERY_VOLTAGE_MIN IS NULL OR BATTERY_VOLTAGE_MIN >= 0) AND
        (BATTERY_VOLTAGE_MAX IS NULL OR BATTERY_VOLTAGE_MAX >= 0) AND
        (MAX_CHARGE_CURRENT IS NULL OR MAX_CHARGE_CURRENT >= 0) AND
        (MAX_DISCHARGE_CURRENT IS NULL OR MAX_DISCHARGE_CURRENT >= 0) AND
        (BATTERY_VOLTAGE_MIN IS NULL OR BATTERY_VOLTAGE_MAX IS NULL OR BATTERY_VOLTAGE_MIN <= BATTERY_VOLTAGE_MAX)
    ),
    CONSTRAINT chk_battery_active CHECK (ACTIVE IN (FALSE, TRUE))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter_system (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    INVERTER_ID INT UNSIGNED NOT NULL,
    SYSTEM_TYPE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_inverter_system (INVERTER_ID, SYSTEM_TYPE),
    KEY idx_system_type (SYSTEM_TYPE),
    CONSTRAINT fk_system_inverter FOREIGN KEY (INVERTER_ID)
        REFERENCES inverter (ID) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE inverter_communication (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    INVERTER_ID INT UNSIGNED NOT NULL,
    COMMUNICATION_TYPE VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_inverter_communication (INVERTER_ID, COMMUNICATION_TYPE),
    KEY idx_communication_type (COMMUNICATION_TYPE),
    CONSTRAINT fk_communication_inverter FOREIGN KEY (INVERTER_ID)
        REFERENCES inverter (ID) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE migration_run (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SOURCE_ID VARCHAR(255) NOT NULL,
    SOURCE_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    SNAPSHOT_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    MAPPING_VERSION VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    DECISIONS_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PLAN_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STATUS VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    STARTED_AT TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    COMPLETED_AT TIMESTAMP(6) NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_migration_input (
        SOURCE_ID, SOURCE_SHA256, SNAPSHOT_SHA256, MAPPING_VERSION, DECISIONS_SHA256
    ),
    CONSTRAINT chk_migration_status CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'FAILED'))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE migration_id_map (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MIGRATION_RUN_ID BIGINT UNSIGNED NOT NULL,
    ENTITY_TYPE VARCHAR(32) NOT NULL,
    SOURCE_KEY VARCHAR(255) NOT NULL,
    TARGET_ID BIGINT UNSIGNED NOT NULL,
    CONTENT_SHA256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY uq_migration_source_mapping (MIGRATION_RUN_ID, ENTITY_TYPE, SOURCE_KEY),
    CONSTRAINT fk_id_map_run FOREIGN KEY (MIGRATION_RUN_ID)
        REFERENCES migration_run (ID) ON DELETE CASCADE ON UPDATE RESTRICT
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE migration_pending (
    ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    MIGRATION_RUN_ID BIGINT UNSIGNED NOT NULL,
    SEVERITY VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    ENTITY_TYPE VARCHAR(32) NOT NULL,
    SOURCE_KEY VARCHAR(255) NOT NULL,
    FIELD_NAME VARCHAR(100) NULL,
    REASON_CODE VARCHAR(64) NOT NULL,
    DETAILS_JSON JSON NULL,
    PRIMARY KEY (ID),
    KEY idx_pending_run_severity (MIGRATION_RUN_ID, SEVERITY),
    CONSTRAINT fk_pending_run FOREIGN KEY (MIGRATION_RUN_ID)
        REFERENCES migration_run (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    CONSTRAINT chk_pending_severity CHECK (SEVERITY IN ('ERROR', 'PENDING', 'WARNING', 'INFO'))
) ENGINE=InnoDB ROW_FORMAT=DYNAMIC DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

